In [8]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy.cluster.hierarchy import dendrogram, linkage
from tslearn.utils import to_time_series_dataset
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.cluster import AgglomerativeClustering
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [ ]:
def ts_cluster_distance(y_pred, df, n_clusters, distance_measure):
    distances = list()
    for cluster in range(n_clusters):
        cluster_center = np.mean(df[y_pred == cluster], axis=0)
        for ts in df[y_pred == cluster]:
            if(distance_measure == "Euclidean"):
                diff = np.sqrt(np.sum((ts.ravel() - cluster_center)**2))
                distances.append(diff)
    return np.mean(distances)

# Bank Reserves

In [9]:
poor = pd.read_csv("SimData/bank_reserves_outputs_poor.csv", header=None)
middle = pd.read_csv("SimData/bank_reserves_outputs_middle.csv", header=None)
rich = pd.read_csv("SimData/bank_reserves_outputs_rich.csv", header=None)

In [13]:
br_poor_ts = to_time_series_dataset(poor)
br_middle_ts = to_time_series_dataset(middle)
br_rich_ts = to_time_series_dataset(rich)

In [11]:
combined = pd.concat([poor, middle, rich], axis=1)
combined = StandardScaler().fit_transform(combined)

k = 7   
kmeans = KMeans(n_clusters=k, random_state=42)
labels = kmeans.fit_predict(combined)

C:\Users\met48\AppData\Local\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] The system cannot find the file specified
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "C:\Users\met48\AppData\Local\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "C:\Users\met48\AppData\Local\anaconda3\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\met48\AppData\Local\anaconda3\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\met48\AppData\Local\anaconda3\Lib\subprocess.py",

In [12]:
labels

array([6, 5, 0, ..., 3, 4, 4])

In [15]:
ts_cluster_distance(labels, br_poor_ts, 7, "Euclidean")

3977.98219752392

In [16]:
ts_cluster_distance(labels, br_middle_ts, 7, "Euclidean")

7545.545921881597

In [17]:
ts_cluster_distance(labels, br_rich_ts, 7, "Euclidean")

4144.924998186655

# Epstein

In [18]:
ecv_active = pd.read_csv("SimData/epsteinCV_outputs_active.csv", header=None)
ecv_jailed = pd.read_csv("SimData/epsteinCV_outputs_jailed.csv", header=None)
ecv_quiet = pd.read_csv("SimData/epsteinCV_outputs_quiet.csv", header=None)

In [19]:
active = to_time_series_dataset(ecv_active)
jailed = to_time_series_dataset(ecv_jailed)
quiet = to_time_series_dataset(ecv_quiet)

In [20]:
combined = pd.concat([ecv_active, ecv_jailed, ecv_quiet], axis=1)
combined = StandardScaler().fit_transform(combined)

k = 8   
kmeans = KMeans(n_clusters=k, random_state=42)
labels = kmeans.fit_predict(combined)

In [21]:
labels

array([2, 4, 5, ..., 4, 4, 1])

In [22]:
ts_cluster_distance(labels, active, 8, "Euclidean")

15374.578709870502

In [23]:
ts_cluster_distance(labels, jailed, 8, "Euclidean")

16884.45670490543

In [24]:
ts_cluster_distance(labels, quiet, 8, "Euclidean")

27407.50932757308

# Forest Fire

In [26]:
def import_ff_data(filename):
    expected_columns=155
    data = []
    with open(filename, 'r') as file:
        for line in file:
            row = line.strip().split(',')
            if len(row) < expected_columns:
                row += [np.nan] * (expected_columns - len(row))
            data.append(row)
    df = pd.DataFrame(data)
    def fill_last_valid(row):
        for i in range(1, len(row)):
            if pd.isna(row[i]):
                row[i] = row[i - 1]  
        return row
    df_filled = df.apply(fill_last_valid, axis=1)
    return df_filled

In [27]:
ff_onfire = import_ff_data("SimData/forest_fire_outputs_onfire.csv")
ff_fine = import_ff_data("SimData/forest_fire_outputs_fine.csv")
ff_burned = import_ff_data("SimData/forest_fire_outputs_burned.csv")

In [31]:
onfire = to_time_series_dataset(ff_onfire)
fine = to_time_series_dataset(ff_fine)
burned = to_time_series_dataset(ff_burned)

In [32]:
combined = pd.concat([ff_onfire, ff_fine, ff_burned], axis=1)
combined = StandardScaler().fit_transform(combined)

k = 4   
kmeans = KMeans(n_clusters=k, random_state=42)
labels = kmeans.fit_predict(combined)

In [33]:
labels

array([3, 1, 1, ..., 1, 0, 2])

In [34]:
ts_cluster_distance(labels, onfire, 4, "Euclidean")

6813.597927437933

In [35]:
ts_cluster_distance(labels, fine, 4, "Euclidean")

235781.35510975076

In [36]:
ts_cluster_distance(labels, burned, 4, "Euclidean")

241855.09660309585